---
name: 'Actions test'

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: ip
      - run: echo ${{ steps.ip.outputs.public-ip }}
